/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ffb4a8",
        "background": "#121414",
        "on-primary": "#690000",
        "on-primary-fixed-variant": "#930100",
        "surface-container-lowest": "#0c0f0f",
        "inverse-primary": "#c00000",
        "surface-bright": "#37393a",
        "primary-fixed": "#ffdad4",
        "tertiary-fixed-dim": "#c8c6c5",
        "primary-fixed-dim": "#ffb4a8",
        "outline": "#b08781",
        "surface": "#121414",
        "error": "#ffb4ab",
        "surface-container-low": "#1a1c1c",
        "tertiary-fixed": "#e4e2e1",
        "on-error": "#690005",
        "on-background": "#e2e2e2",
        "on-tertiary-fixed-variant": "#474746",
        "surface-container-highest": "#333535",
        "inverse-surface": "#e2e2e2",
        "surface-variant": "#333535",
        "error-container": "#93000a",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-container": "#474746",
        "surface-container-high": "#282a2b",
        "on-tertiary-container": "#fbf8f8",
        "secondary-fixed": "#e5e2e1",
        "surface-dim": "#121414",
        "on-secondary": "#313030",
        "surface-tint": "#ffb4a8",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#5f3f3a",
        "on-surface-variant": "#e9bcb5",
        "secondary": "#c8c6c5",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary-container": "#fff7f5",
        "inverse-on-surface": "#2f3131",
        "tertiary": "#c8c6c5",
        "on-tertiary": "#303030",
        "surface-container": "#1e2020",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#b7b5b4",
        "secondary-fixed-dim": "#c8c6c5",
        "on-surface": "#e2e2e2",
        "tertiary-container": "#737272",
        "primary-container": "#e60000",
        "on-primary-fixed": "#410000"
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px"
      },
      spacing: {
        unit: "4px",
        "section-gap": "120px",
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        gutter: "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "data-label": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
